drop table member;

select * from member;

create table member(
	MEMBER_ID	VARCHAR2(50) PRIMARY KEY,
	MEMBER_NAME VARCHAR2(50) NOT NULL,
	MEMBER_PASS VARCHAR2(50) NOT NULL,
	MEMBER_BIRTH VARCHAR2(50) NOT NULL,
	MEMBER_GENDER VARCHAR2(50) NOT NULL,
	MEMBER_EMAIL VARCHAR2(50) NOT NULL,
	MEMBER_TEL VARCHAR2(50) NOT NULL,
	MEMBER_BANK VARCHAR2(50),
	MEMBER_ACCOUNT VARCHAR2(50),
	MEMBER_POST VARCHAR2(50) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(300) NOT NULL,
	MEMBER_I_CA VARCHAR2(50) ,
	MEMBER_PFPH VARCHAR2(200)
);
